### ISSUE TITLE
Get category of each item return from collection

### ISSUE THREAD

**Issue by christill** [WP-API/client-js#110]
When trying to call `getCategories()` on a model within a collection it return the error: 
`a.at(...).getCategories is not a function`

If i wrap the first result of the collection in a new model. it works. Is it necessary to create a new model for each item returned from a collection or am I doing something wrong?

Thanks

**Comment by adamsilverstein** [comment]
@christill 

It sounds like you are using an outdated version of the library. 

Can you make sure you are using the latest code from this plugin? Install this repository as a plugin, then make sure SCRIPT_DEBUG is on in wp-config.

If it still fails, can you share a code block so I can see what you are trying? Thanks.

**Comment by adamsilverstein** [comment]
@christill 

You will find the latest changes in the WP-API plugin now, and getCategories should work  correctly. Please note that this function returns a promise because the function may need to make an ajax request to complete. I updated the docs to reflect this, you can use as follows:

```js
post.getCategories().done( function( postCategories ) {
	// ... do something with the postCategories array.
	
} );
```

Please re-open or ping me in slack rest-api room if you are still having trouble.

**Comment by adamsilverstein** [comment]
@christill when working on another issue I revisited this issue and realized we didn’t actually solve the issue you were experiencing. We did manage to fix it in WordPress core where development is continuing. If you have a moment, can you try out the patch on https://core.trac.wordpress.org/ticket/39070 to see if it resolves the issue.
