### ISSUE TITLE
Settings is incorrectly registered as a collection

### ISSUE THREAD

**Issue by rmccue** [WP-API/client-js#167]
`/wp/v2/settings` is a model, not a collection. This is incorrectly detected due to the JS code assuming anything not ending with a regex is a collection, which is not true.

Potentially, we need to change the API to better expose what is and isn't a collection to the JS. The schema in the returned OPTIONS currently indicates that the response is an object, whereas it's actually a list of objects. If we change this, we need to look carefully at how we retrofit this, as changing it may break compatibility.

**Comment by adamsilverstein** [comment]
Correct, currently the client assumes that routes ending in a word (eg 'settings') are parsed as collections, and routes ending in a regex are considered a singular model. This aligns well with typical REST endpoints, however there are exceptions. In core, the only exception is '/me' with returns a single model of data, not a collection.

I would love a way to determine model or collection based on an option value rather than relying on the route assumption. I think we have to somehow add this data to the endpoints as we create them, and perhaps the client should fall back to the existing approach if the schema doesn't contain the data.

**Comment by rmccue** [comment]
> In core, the only exception is '/me' with returns a single model of data, not a collection.

As mentioned, `/settings` is also a model, not a collection.

We should discuss how best to expose collections vs models via the API. Changing the schema is the best way, I think. See https://github.com/WP-API/proposals/issues/2 for that discussion.

In the meantime, we should special-case `/settings` as well.

**Comment by adamsilverstein** [comment]
Closing in favor of https://core.trac.wordpress.org/ticket/41056#ticket
