### ISSUE TITLE
Draft posts throw invalid time value error

### ISSUE THREAD

**Issue by josiahgoff** [WP-API/client-js#23]
When running `toJSON()` on a post object that has a status of 'draft', it throws an error because we're trying to run `toISOString()` on `null`, since there is no date for an unpublished post.

Found here: https://github.com/WP-API/client-js/blob/gh-pages/js/models.js#L32

![screen shot 2014-09-30 at 11 51 56 am](https://cloud.githubusercontent.com/assets/684774/4464359/26b9924a-48d3-11e4-9680-90ae3d7a6fdb.png)

Should be a quick fix. I'd do it myself, but the build process is currently broken on my machine for some reason.

**Comment by adamsilverstein** [comment]
@josiahgoff 

Thanks for reporting this issue. This should be corrected in the latest version of the library, in the [develop branch](https://github.com/WP-API/client-js/tree/develop).

Here is a sequence showing saving a new post in the console, can you please retest and see if this resolves the issue for you? Since I'm seeing this fixed, I'm marking as resolved, please reopen if you still have an issue.

[Screenshot](http://cl.ly/3H0W2F3m0a1h/This_is_nice__Just_another_WordPress_site_2015-12-11_19-47-15.jpg)
