### ISSUE TITLE
Need {add: true} when fetching pagination

### ISSUE THREAD

**Issue by josiahgoff** [WP-API/client-js#26]
We need to pass in `{add: true}` when grabbing the next page in the `more()` method. Right now it's duplicating the first page in the collection when the method is called.

https://github.com/WP-API/client-js/blob/gh-pages/js/collections.js#L109

**Comment by adamsilverstein** [comment]
Hi @josiahgoff - Thank you for your report.

Can you please recheck with the current version of the plugin in the develop branch? It and the API have undergone some significant revisions and I believe this issue is resolved.

I am able to use the more command correctly. Here is a screenshot of me using the more command with a post collection in the console. I always seem to get the expected posts in my test setup.

![Screenshot](http://cl.ly/2C1O3S3H0I3D/This_is_nice__Just_another_WordPress_site_2015-12-12_16-27-10.jpg)

If you can reproduce, please provide a code snippet we can test with.

Thanks!

**Comment by adamsilverstein** [comment]
Closing as resolved, I have tested this and its now working.
