### ISSUE TITLE
collection.create() got 400 error?

### ISSUE THREAD

**Issue by demixpress** [WP-API/client-js#46]
Hi, 

I tried to create new post in backbone way:

<pre>
var posts = new wp.api.collections.Posts();
var data = {
        title: 'Title'
    };
posts.create(data);
</pre>

and got a 400 error:

POST http://192.168.1.107/demo/wp-json/wp/v2/posts 400 (Bad Request)

but the jquery way is working:
<pre>
$.ajax({
        method: "POST",
        url: WP_API_Settings.root + 'wp/v2/posts',
        data: data,
        beforeSend: function ( xhr ) {
            xhr.setRequestHeader( 'X-WP-Nonce', WP_API_Settings.nonce );
        },
        success : function( response ) {
            console.log( response );
        },
        fail : function( response ) {
            console.log( response );
        }
    });
</pre>

Did I missing anything?

**Comment by adamsilverstein** [comment]
Hi @demixpress! Thanks for the bug report.

I have been working on our model implementation and tested creating a new post using the model wp.api.models.Post 

After a fix, I got it working - here was my test code:

{{{
var post = new wp.api.models.Post();
var data = {
		title: 'This is a test post.'
	};
post.save( data );

}}

It turns out there was a bug in the model for a single post that prevented it working to create a new post. I have updated the model code and the JS library in master, can you try out this latest version?

I will be working on our collections soon and make will test your code there again, I'm guessing its a similar issue.

**Comment by adamsilverstein** [comment]
Verified the code from your original snippet now works:

```
var posts = new wp.api.collections.Posts();
var data = {
		title: 'Title'
	};
posts.create(data);
```

**Comment by adamsilverstein** [comment]
Closing as resolved, thanks again for the bug report.
