### ISSUE TITLE
Model defaults are set incorrectly?

### ISSUE THREAD

**Issue by rmccue** [WP-API/client-js#79]
Phew, so, this took me a while. Here's the problem:

* `wp.api.models.Post.prototype.defaults` no longer exists :(
* `wp.api.models.Post.defaults` does exist, but contains useless properties, and I'm 90% certain it's not meant to be used for model defaults.

Not sure if this is intentional? Essentially, what's happening is that the args from POST/PUT are used for the model's defaults, although it's assigned to the constructor object, not to the prototype. The real defaults are under `Post.options` instead, but not in a directly usable form.

In my subclass, I'm defining `MyPost.prototype.defaults`, which previously took `wp.api.models.Post.prototype.defaults()` and added extra properties.

Is this an intentional change? Having the defaults is nice, because it means you can optimistically render the object while it saves.

**Comment by adamsilverstein** [comment]
@rmccue -

Thanks for tracking this down and bringing it up, I will review. The change was not intentional, there has been some churn in the defaults

The defaults are currently being grabbed from each endpoint; I agree they should be applied to the prototype (as a property though, you indicate its a function return above, were you really using it that way?)

I'm currently traversing the POST endpoint and using `args` as defaults. these are returned as objects and I recently changed the handling of these to leave them as objects instead of transforming them which broke caching. is the return of default values as objects by the api expected? see - http://cl.ly/400V1837162N/wpdev.localhostwp-json_2016-01-14_09-26-09.jpg

I also learned recently about `?context=help` which adds additional schema info to each endpoint; thinking about adding this info into the models as well, not sure where.

**Comment by rmccue** [comment]
> as a property though, you indicate its a function return above, were you really using it that way?

Backbone supports either using `_.result()`, similar to how `.url` can be a property or a function. I need the function variant for the deferred/JIT processing.

> I'm currently traversing the POST endpoint and using args as defaults. these are returned as objects and I recently changed the handling of these to leave them as objects instead of transforming them which broke caching. is the return of default values as objects by the api expected?

The screenshot here actually shows _no_ default values; the arg object is options for that argument, not just the default. It looks like we don't have default values set for the POST, so we shouldn't be using the rest as the "default".

I have a patch to handle this if you're :+1:

**Comment by adamsilverstein** [comment]
I'm :+1: PR that patch and I will review/merge :)

**Comment by adamsilverstein** [comment]
Fixed in https://github.com/WP-API/client-js/pull/85, thanks!
