### ISSUE TITLE
wpApiSettings is not defined

### ISSUE THREAD

**Issue by MurhafSousli** [WP-API/client-js#87]
Hi, I tried to include the script `wp-api.min.js` from the build dir, I get this exception 

`Uncaught ReferenceError: wpApiSettings is not defined(anonymous function) @ models.js:114`

how can I fix this error?

**Comment by kadamwhite** [comment]
I could be wrong (@adamsilverstein is the authority here), but I believe that this script is designed to be enqueued through WordPress, so that WP's script localization capabilities can inject that configuration object based on your specific WP install. Is there a reason you need to hard-code a script tag for the client JS rather than using the enqueue script method?

**Comment by rmccue** [comment]
> I believe that this script is designed to be enqueued through WordPress

In fact, it's required to be, you can't use it outside of WP.

**Comment by MurhafSousli** [comment]
I'm using wp rest api to get data for my angular2 app.

**Comment by rmccue** [comment]
You need to use an alternative library and authentication method to access the API outside WP.

**Comment by adamsilverstein** [comment]
@MurhafSousli This library is indeed currently designed to be enqueued from WordPress, however your question brings up an interesting point: can we remove the WordPress dependency?

* For non authenticated requests, this library should work fine without WordPress. I will work on removing the dependency.
* I am currently working on adding support for other authentication methods (oAuth, application passwords) that would not require a WordPress generated nonce and cookie for authenticated actions
